### ISSUE TITLE
Rewards not working properly!

### ISSUE THREAD

**Issue by Pyario** [Maxlego08/zVoteParty#4]
I have 4 rewards. One of these is at 100 percent but I'm not getting it at 100%.
 100% means for me that it always gets! Please fix. Latest Version: 1.0.2.2
 
 Config:
 
rewards:
  1:
    percent: 100
    needToBeOnline: false # Player must not be online to receive the reward
    commands:
      - "givekey %player%"
    broadcast:
    - "§"
  2:
    percent: 10
    needToBeOnline: false # Player must not be online to receive the reward
    commands:
      - "eco add %player% 250"
    broadcast:
    - "§r"
  3:
    percent: 10
    needToBeOnline: true # Player must not be online to receive the reward
    commands:
      - "minecraft:give %player% minecraft:cooked_beef 16"
    broadcast:
    - "§5"
  4:
    percent: 1
    needToBeOnline: true # Player must not be online to receive the reward
    commands:
      - "minecraft:give %player% minecraft:diamond 1"
    broadcast:
    - "§r" 
    
    Best Regards,
    
    Pyario

**Comment by Abasing** [comment]
Hey! You should remove all other rewards if that's what you want. That's the best possibility as plugin is currently under quarantine.
