### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by ghost** [Maxlego08/zVoteParty#6]
Checking event.getView().getTitle() to see whether your custom inventory is being used is unsafe, as renaming a chest in an anvil allows users to set their own inventory titles. The correct way to check if your custom inventory is involved with an event is by using custom holders, see here: https://docs.papermc.io/paper/dev/custom-inventory-holder

https://github.com/Maxlego08/zVoteParty/blob/b6d407a53c32e491f83fbe6fa6367457034fd778/src/fr/maxlego08/zvoteparty/inventory/ZInventoryManager.java#L119

**Comment by Maxlego08** [comment]
Hey, zVoteParty doesnt use this inventory system, now its zMenu
